Exception
NorthDragons/fimls-back pull request #2
Opened 2022-12-27 11:14 UTC by NorthDragons

Creating a custom error MovieNotFoundException. 
Implementation of ExceptionHandler with unexpected errors in mind. 
Creating a DAO for more convenient unit testing using mocks. 
Adding forwarding errors when trying to delete a non-existent movie and also when trying to get a non-existent movie

2022-12-27 12:19 UTC, yuraf640 commented on src/main/java/com/netflix/sandBox/dao/MovieDaoImpl.java
> +    public Optional<Movie> getById(Long id) {
FYI. It's not the best practice to use Optional just for validation for null. It's not good if your controller returns null, but for DAO it's normal, because DAO it's just a connection layer, it's prepare query and return value, and DAO does not responsible  for the return value because you have service layer which responsible for it. You can leave it as it is for now, but pay attention to this in future

2022-12-27 12:29 UTC, yuraf640 commented on src/main/java/com/netflix/sandBox/dao/MovieDaoImpl.java
> +        movies.put(randomId, movie);
One important thing that i missed in previous PR is - synchronization. You need to synchronize all **movies** operations (read and wright) just to be sure that two different treads cannot modify it in the same time.
Create mutex objects to synchronize access to data structures:
1)private static final MOVIE_MUTEX = new Object();
2) synchronized (MOVIE_MUTEX ) {
// do something
}

2022-12-27 12:38 UTC, yuraf640 commented on src/main/java/com/netflix/sandBox/exception/ApiError.java
> +    @JsonInclude(JsonInclude.Include.NON_NULL)
1) You have constructor without parameters and i think this is strange, because there are should be some message.
2) If you use this annotation - please use it for all fields that potentially could be null. I your case it's all fields because you have constructor without parameters

2022-12-27 12:43 UTC, yuraf640 commented on src/main/java/com/netflix/sandBox/exception/MovieExceptionHandler.java
> +    @ExceptionHandler(MethodArgumentTypeMismatchException.class)
Where did you get this exception?

2022-12-27 12:46 UTC, yuraf640 commented on src/main/java/com/netflix/sandBox/exception/MovieExceptionHandler.java
> +    protected ResponseEntity<Object> handleHttpMessageNotReadable(HttpMessageNotReadableException ex, HttpHeaders headers,
HttpMessageNotReadableException - i cannot find throwing of this exception in this PR

2022-12-27 12:48 UTC, yuraf640 commented on src/main/java/com/netflix/sandBox/exception/MovieExceptionHandler.java
> +    protected ResponseEntity<Object> handleNoHandlerFoundException(
the same... Please remove all handlers that you not need.

2022-12-27 12:53 UTC, yuraf640 commented on src/main/java/com/netflix/sandBox/service/MovieServiceImpl.java
> +    private List<Movie> sortMovies(List<Movie> movies, List<String> genres) {
It's not **sort** but **filter**

2022-12-27 13:07 UTC, yuraf640 commented on src/main/java/com/netflix/sandBox/modal/Movie.java
> +    @Override
Do you really need override **equals** and **hashCode**? I can't see the reason, show me please

2022-12-27 13:08 UTC, yuraf640 commented on src/main/java/com/netflix/sandBox/modal/Movie.java
> +@Builder
If you not use some annotation - please remove it

2022-12-27 13:12 UTC, yuraf640 requested changes
Please pay attention to the comments

2022-12-27 13:46 UTC, NorthDragons commented on src/main/java/com/netflix/sandBox/modal/Movie.java
> +    @Override
I am using Set in movie filtering

2022-12-27 13:48 UTC, NorthDragons commented on src/main/java/com/netflix/sandBox/modal/Movie.java
> +@Builder
I use Builder when writing unit tests. So far I have not included a class with tests in the pull request, but in the future the annotation will be used

2022-12-28 10:02 UTC, yuraf640 commented on src/main/java/com/netflix/sandBox/dao/MovieDaoImpl.java
> +            if (movies.containsKey(id)) {
All operations with movies must be synchronized, delete also.

2022-12-28 10:08 UTC, yuraf640 commented on src/main/java/com/netflix/sandBox/modal/Movie.java
> +    @Override
Ok, but why you need override it? Does not it work without overriding?

2022-12-28 10:16 UTC, yuraf640 approved these changes
Looks good. Please set **ALL** operations  with movies synchronized and you can merge it.

2022-12-28 10:30 UTC, merged